### ISSUE TITLE
Publish somewhere

### ISSUE THREAD

**Issue by katjam** [CodeReadingClubs/pdf-maker#1]
Glitch was too slow to be used by public.

We discussed heroku, katja's droplet, or netlify

@danfishgold - post any progress here. I'm not assigning to you, but have done nothing yet, myself and thought it would be good to keep each other in the loop via issue!

**Comment by danfishgold** [comment]
I ran into an issue with netlify functions (I got an error saying I had to return a string response) but I found [a workaround](https://github.com/storybookjs/shout-out-kit/blob/main/functions/shout-out-image/shout-out-image.js#L79) (encode the pdf buffer with base64) so it's all good now 😄

I can put up a _very_ basic page with an input box where you could paste the github url and get the generated pdf for now, but I think eventually we should incorporate this into the main site. what do you think?

**Comment by katjam** [comment]
Awesome! 

yes to "incorporate into main site"

If it's easy to do that, put up a PR - if it's not, do the basic page simple box and we can link out to it.

**Comment by danfishgold** [comment]
I'm not familiar with elm pages so I'll do the basic page for now

**Comment by katjam** [comment]
Sounds like a good plan.
