### ISSUE TITLE
Feature Request: syntax highlighting

### ISSUE THREAD

**Issue by Sm4o** [CodeReadingClubs/pdf-maker#5]
Nice work! This could be useful for sharing code via email for example without worrying about formatting or the email getting too big.

A feature I would like to suggest is syntax highlighting for different languages. Perhaps using something like [highlight.js](https://highlightjs.org/) or [prism.js](https://prismjs.com/). Let me know if you think this is doable.

**Comment by katjam** [comment]
HI @Sm4o Thanks for your feature request. It's a  commonly asked question.

At the moment, we have no plans to add syntax highlighting to this or our other tools. One of the skills we are practising with code reading is teaching our brains to read the code without helpers like this. If we get good without the highlighting then the highlights are a bonus and can serve to make it even easier for us.

We do this deliberate practice as a different type of training to the practice we get with using our tool at work.
